//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityProjectTemplates.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnityProjectTemplates.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity Image Effect Shader.
        /// </summary>
        public static string UnityImageEffectShader {
            get {
                return ResourceManager.GetString("UnityImageEffectShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity MonoBehaviour.
        /// </summary>
        public static string UnityMonoBehaviour {
            get {
                return ResourceManager.GetString("UnityMonoBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity ScriptableObject.
        /// </summary>
        public static string UnityScriptableObject {
            get {
                return ResourceManager.GetString("UnityScriptableObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity StateMachineBehaviour.
        /// </summary>
        public static string UnityStateMachineBehaviour {
            get {
                return ResourceManager.GetString("UnityStateMachineBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity Surface Shader.
        /// </summary>
        public static string UnitySurfaceShader {
            get {
                return ResourceManager.GetString("UnitySurfaceShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity.
        /// </summary>
        public static string UnityTemplateCategory {
            get {
                return ResourceManager.GetString("UnityTemplateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity Test Case.
        /// </summary>
        public static string UnityTestCase {
            get {
                return ResourceManager.GetString("UnityTestCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity Unlit Shader.
        /// </summary>
        public static string UnityUnlitShader {
            get {
                return ResourceManager.GetString("UnityUnlitShader", resourceCulture);
            }
        }
    }
}
